#!/bin/bash

INITIAL=0

if [ "$GIT_DIR"x == "x" ]; then
    GIT_DIR=/home/qcadmin/dns/.git
    INITIAL=1
fi

WORKDIR=$GIT_DIR/../

# Copy in the config
cp $WORKDIR/nsd.conf.master /etc/nsd/nsd.conf
cp -r $WORKDIR/zones /etc/nsd

# Reload the process
if [ INITIAL -eq 0 ]; then
    nsd-control reload
fi
