#!/bin/bash

set -e
set -u

ZONES=(at.quakecon.org quakeconcdn.org 172.in-addr.arpa)

# Update Master
cp nsd.conf.master /etc/nsd/nsd.conf
cp -r zones /etc/nsd

for SECONDARY in 172.16.1.102 172.16.1.103 172.16.1.104; do
    scp nsd.conf.slave qcadmin@${SECONDARY}:/etc/nsd/nsd.conf
    ssh qcadmin@${SECONDARY} nsd-control reconfig
    
    scp unbound.conf qcadmin@${SECONDARY}:/etc/unbound/unbound.conf
    ssh qcadmin@${SECONDARY} unbound-control reconfig
    for ZONE in $ZONES; do
	ssh qcadmin@${SECONDARY} unbound-control flush_zone $ZONE
    done
done
